name: 'Commit Check Regex'
description: 'Wait a designated number of milliseconds'
inputs:
  items:  # id of input
    description: 'array of regular expressions'
    required: true
    default: '.*'
outputs:
  items: # output will be available to future steps 
    description: 'array of booleans corresponding to inputs'
runs:
  using: 'node12'
  main: 'dist/index.js'
